POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "God go help someone.",
    "author": "Musthu Karunan",
    "url": "www.someonegod.com",
    "likes": 54,
    "id": "64b553b2cf142822477c37b8"   
}

###
GET http://localhost:3001/api/blogs

###

GET http://localhost:3001/api/blogs/649eafc26b5783a62e134c35

###
PUT http://localhost:3001/api/blogs/649eafc26b5783a62e134c35
Content-Type: application/json

{
    "likes": 102
}
###
DELETE http://localhost:3001/api/blogs/649dc47baf23115bcc6c5f4

