POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "June 13",
    "author": "Roshith Krishna P",
    "url": "www.june13.com",
    "likes": 113   
}

###
GET http://localhost:3001/api/blogs

###

GET http://localhost:3001/api/blogs/6a06dd09325701604facd3d

###
PUT http://localhost:3001/api/blogs/649eafc26b5783a62e134c35
Content-Type: application/json

{
    "likes": 102
}
###
DELETE http://localhost:3001/api/blogs/649dc47baf23115bcc6c5f4

