POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Mere Avaas Suno",
    "author": "Roshith Krishna P",
    "url": "www.mas.com",
    
}

###
GET http://localhost:3001/api/blogs

###
DELETE http://localhost:3001/api/blogs/649eaf016b5783a62e134c33

